#!/usr/bin/env python3
"""Generate documentation data through sniff's public CLI."""

import json
from pathlib import Path
import subprocess
import sys

import yaml

ROOT = Path(__file__).resolve().parents[1]
PROFILES = ("document", "prompt", "spec", "code", "all")


def output(binary: Path, profile: str, kind: str) -> str:
    return subprocess.run(
        [str(binary), "rules", "--target", str(ROOT), "--profile", profile,
         "--format", kind],
        cwd=ROOT, check=True, capture_output=True, text=True,
    ).stdout


def main() -> None:
    binary = Path(sys.argv[1] if len(sys.argv) > 1 else ROOT / "target/debug/sniff")
    if not binary.is_file():
        raise SystemExit(f"sniff binary not found: {binary}; run cargo build first")
    profiles = {}
    for profile in PROFILES:
        rules = [json.loads(line) for line in output(binary, profile, "jsonl").splitlines()]
        profiles[profile] = {
            "rules": [rule["id"] for rule in rules],
            "prompt": output(binary, profile, "llm"),
        }
    registry = []
    pages = ROOT / "docs/generated/rules"
    pages.mkdir(parents=True, exist_ok=True)
    for stale in pages.glob("*.md"):
        stale.unlink()
    for path in sorted((ROOT / "rules").glob("*.md")):
        _, frontmatter, guidance = path.read_text().split("---", 2)
        metadata = yaml.safe_load(frontmatter)
        rule = {
            "id": metadata["id"],
            "code": metadata["code"],
            "name": metadata["name"],
            "family": metadata["family"],
            "applies_to": metadata["applies_to"],
            "severity": metadata["severity"],
            "message": metadata["message"],
            "fix": metadata.get("fix", "manual"),
            "evidence": metadata.get("evidence", ""),
            "llm_exempt": metadata.get("llm_exempt", False),
            "sniffers": metadata["sniffers"],
            "guidance": guidance.strip(),
        }
        registry.append(rule)
        write_rule_page(pages, rule)
    profiles = {
        "registry": {"rules": [rule["id"] for rule in registry], "prompt": None},
        **profiles,
    }
    payload = {"profiles": profiles, "rules": registry}
    target = ROOT / "docs/generated/rules.js"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("window.SNIFF_DOCS = " + json.dumps(payload, indent=2) + ";\n")
    print(f"wrote {target.relative_to(ROOT)} with {len(registry)} bundled rules")


def write_rule_page(directory: Path, rule: dict) -> None:
    sniffers = ", ".join(sniffer["kind"] for sniffer in rule["sniffers"])
    evaluation = "detector only" if rule["llm_exempt"] else "LLM"
    profiles = ", ".join(f"`{value}`" for value in rule["applies_to"])
    detector_metadata = yaml.safe_dump(
        rule["sniffers"], sort_keys=False, default_flow_style=False
    ).rstrip()
    page = f"""<!-- Generated by docs/build.py. Do not edit directly. -->
# {rule['name']} ({rule['code']})

{rule['message']}

| Metadata | Value |
|---|---|
| Rule ID | `{rule['id']}` |
| Family | {rule['family']} |
| Applies to | {profiles} |
| Default severity | `{rule['severity']}` |
| Fix | `{rule['fix']}` |
| Evidence | {rule['evidence'] or '—'} |
| Sniffers | {sniffers} |
| Contextual evaluation | {evaluation} |

{rule['guidance']}

## Detector metadata

```yaml
{detector_metadata}
```

[View rule source](https://github.com/fstermann/sniff/blob/main/rules/{rule['id']}.md)
"""
    (directory / f"{rule['id']}.md").write_text(page)


if __name__ == "__main__":
    main()
